# 参照定義ファイル：
# MEP/definitions/SYMBOLS.md
#
# 本ファイル内に出現する参照記号は、
# 個別宣言や列挙を行わず、
# 上記参照定義ファイルを唯一の正として解決する。
#
# 本ファイルは参照関係の宣言・管理を行わない。



name: Post Merge Maintenance

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  clean-generated-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean generated_output folder
        run: |
          echo "Cleaning generated_output/"
          rm -rf generated_output/*
          echo "Cleanup done."

      - name: Commit cleanup changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add generated_output
          git commit -m "chore: clean generated_output after merge" || echo "No changes to commit"
          git push

