# 参照定義ファイル：
# MEP/definitions/SYMBOLS.md
#
# 本ファイル内に出現する参照記号は、
# 個別宣言や列挙を行わず、
# 上記参照定義ファイルを唯一の正として解決する。
#
# 本ファイルは参照関係の宣言・管理を行わない。



name: clean-generated-output

on:
  push:
    branches: [ main ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove generated outputs
        run: |
          rm -rf generated

      - name: Fail if generated outputs are committed
        run: |
          if [ -d "generated" ]; then
            echo "generated directory must not be committed"
            exit 1
          fi
