# 参照定義ファイル：
# MEP/definitions/SYMBOLS.md
#
# 本ファイル内に出現する参照記号は、
# 個別宣言や列挙を行わず、
# 上記参照定義ファイルを唯一の正として解決する。
#
# 本ファイルは参照関係の宣言・管理を行わない。



name: Compiler Test

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test-run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MODE: "full"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install OpenAI package
        run: pip install openai

      - name: Run compiler_engine.py
        run: python compiler/compiler_engine.py

      - name: Upload UI questions
        uses: actions/upload-artifact@v4
        with:
          name: ui-questions
          path: questions.txt

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          path: generated_output
          if-no-files-found: ignore

      - name: Create Pull Request for generated code
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "auto: update generated code"
          title: "Auto: Update generated code"
          body: |
            このPRはコンパイラ workflow により自動生成されました。
            mode: full
          branch: "auto/generated-code"
          delete-branch: true
          add-paths: |
            generated_output/**
