#!/usr/bin/env python3
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RUN_STATE = REPO / "mep" / "run_state.json"
RUNNER = REPO / "tools" / "runner" / "runner.py"
BASE_BRANCH = "main"
SSOT_PATHS = [
  "mep/run_state.json",
  "docs/MEP/STATUS.md",
  "docs/MEP/HANDOFF_AUDIT.md",
  "docs/MEP/HANDOFF_WORK.md",
]
REASON_CODE_RULES = {
  "EVIDENCE_REQUIRED_BUT_UNAVAILABLE": {
    "category": "rerun canonical evidence probe",
    "runner_cmd": "pr-probe",
  },
  "LOOP_ENTRY_DISPATCH_FAILED": {
    "category": "rerun canonical loop entry",
    "runner_cmd": "loop-resume",
  },
  "LOOP_ENGINE_CHILD_STATE_UNAVAILABLE": {
    "category": "rerun canonical engine refresh",
    "runner_cmd": "loop-wait-refresh",
  },
  "LOOP_ENGINE_CHILD_STATE_UNAVAILABLE_PERSISTENT": {
    "category": "hard stop",
    "stop": "hard",
  },
  "LOOP_CONTEXT_INVALID": {
    "category": "freeze to canonical status view",
    "runner_cmd": "status",
    "requires_run_id": False,
  },
  "LOOP_ENGINE_COMPLETED_WITH_FAILURE": {
    "category": "rerun canonical engine refresh",
    "runner_cmd": "loop-wait-refresh",
  },
  "LOOP_ENGINE_RUN_UNRESOLVED": {
    "category": "rerun canonical loop entry after unresolved engine wait",
    "runner_cmd": "loop-resume",
  },
  "LOOP_ENGINE_RUN_UNRESOLVED_PERSISTENT": {
    "category": "hard stop",
    "stop": "hard",
  },
  "LOOP_REPO_UNRESOLVED": {
    "category": "freeze to canonical status view",
    "runner_cmd": "status",
    "requires_run_id": False,
  },
  "LOOP_RESUME_ACTION_UNSUPPORTED": {
    "category": "freeze to canonical status view",
    "runner_cmd": "status",
    "requires_run_id": False,
  },
  "LOOP_WAIT_ACTION_UNSUPPORTED": {
    "category": "freeze to canonical status view",
    "runner_cmd": "status",
    "requires_run_id": False,
  },
  "MULTIPLE_PR_FOR_ONE_RUN": {
    "category": "rerun canonical evidence probe",
    "runner_cmd": "pr-probe",
  },
}
def stop_wait(code: str, msg: str):
  print(f"STOP_WAIT: {code}\n{msg}", file=sys.stderr)
  return 2
def stop_hard(code: str, msg: str):
  print(f"STOP_HARD: {code}\n{msg}", file=sys.stderr)
  return 1
def _run(cmd: list[str]) -> int:
  p = subprocess.run(cmd, text=True, encoding="utf-8", errors="replace")
  return p.returncode


def _run_text(cmd: list[str], check: bool = True) -> str:
  p = subprocess.run(
    cmd,
    cwd=REPO,
    text=True,
    encoding="utf-8",
    errors="replace",
    capture_output=True,
  )
  if check and p.returncode != 0:
    raise RuntimeError(p.stderr.strip() or p.stdout.strip() or f"command failed: {' '.join(cmd)}")
  return p.stdout


def _sanitize_run_id(run_id: str) -> str:
  out = []
  for c in run_id:
    out.append(c if (c.isalnum() or c in "-_.") else "-")
  s = "".join(out).strip("-.")
  return s or "unknown-run"


def _runner_cmd_from_reason_code(reason_code: str, run_id: str) -> list[str] | None:
  rule = REASON_CODE_RULES.get(str(reason_code or "").strip())
  if not rule:
    return None
  runner_cmd = str(rule.get("runner_cmd") or "").strip()
  if not runner_cmd:
    return None
  requires_run_id = bool(rule.get("requires_run_id", True))
  if not requires_run_id:
    return ["python", str(RUNNER), runner_cmd]
  if not run_id:
    raise RuntimeError(f"reason_code={reason_code} requires run_id")
  return ["python", str(RUNNER), runner_cmd, "--run-id", run_id]


def _stop_from_reason_code(reason_code: str, stop_class: str) -> int | None:
  rule = REASON_CODE_RULES.get(str(reason_code or "").strip())
  if not rule:
    return None
  category = str(rule.get("category") or "").strip()
  if str(rule.get("stop") or "").strip() == "hard":
    return stop_hard(reason_code or "MANUAL_RESOLUTION_REQUIRED", f"reason_code={reason_code} category={category} stop_class={stop_class}")
  return None


def _ensure_ssot_writeback_pr(run_id: str) -> tuple[bool, str | None]:
  changed = _run_text(["git", "status", "--porcelain", "--", *SSOT_PATHS]).strip()
  is_dirty = bool(changed)
  print(f"SSOT_DIRTY={'true' if is_dirty else 'false'}")
  if not is_dirty:
    return False, None

  safe_run_id = _sanitize_run_id(run_id)
  branch = f"mep/state-update/{safe_run_id}"
  title = f"chore(mep): persist SSOT state for {run_id}"
  body = "\n".join([
    "Automated SSOT writeback from self-heal auto-resume.",
    "",
    f"- run_id: {run_id}",
    f"- source: {datetime.now(timezone.utc).isoformat()}",
    "",
    "This PR persists mep/run_state.json and compiled MEP documents generated by runner.",
  ])

  _run_text(["git", "config", "user.name", "github-actions[bot]"])
  _run_text(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"])
  _run_text(["git", "checkout", "-B", branch])
  _run_text(["git", "add", "--", *SSOT_PATHS])
  staged = _run_text(["git", "diff", "--cached", "--name-only"]).strip()
  if not staged:
    print("SSOT_DIRTY=false")
    return False, None
  _run_text(["git", "commit", "-m", f"chore(mep): persist SSOT state for {run_id}"])
  _run_text(["git", "push", "--force-with-lease", "origin", f"HEAD:{branch}"])

  prs_raw = _run_text([
    "gh", "pr", "list",
    "--state", "open",
    "--base", BASE_BRANCH,
    "--head", branch,
    "--json", "number,url",
    "--limit", "1",
  ])
  prs = json.loads(prs_raw or "[]")
  if prs:
    pr_number = str(prs[0]["number"])
    pr_url = prs[0]["url"]
  else:
    pr_url = _run_text([
      "gh", "pr", "create",
      "--base", BASE_BRANCH,
      "--head", branch,
      "--title", title,
      "--body", body,
    ]).strip()
    pr_number = _run_text(["gh", "pr", "view", pr_url, "--json", "number", "--jq", ".number"]).strip()

  _run_text(["gh", "pr", "merge", pr_number, "--auto", "--squash"], check=False)
  print(f"SSOT_PR_URL={pr_url}")
  return True, pr_url
def main() -> int:
  if not RUN_STATE.exists():
    return stop_hard("RUN_STATE_MISSING", "mep/run_state.json not found")
  try:
    rs = json.loads(RUN_STATE.read_text(encoding="utf-8"))
  except Exception as e:
    return stop_hard("RUN_STATE_INVALID_JSON", str(e))
  run_id = str(rs.get("run_id") or "").strip()
  next_action = str(rs.get("next_action") or "").strip()
  lr = rs.get("last_result") or {}
  stop_class = str(lr.get("stop_class") or "").strip()
  loop_state = rs.get("loop_state") if isinstance(rs.get("loop_state"), dict) else {}
  reason_code = str(lr.get("reason_code") or loop_state.get("reason_code") or "").strip()
  if not next_action:
    return stop_hard("NEXT_ACTION_MISSING", "run_state.next_action is empty")
  loop_actions = {
    "SSOT_SCAN",
    "CONFLICT_SCAN",
    "EXTRACT_GENERATE",
    "WRITEBACK_PREFLIGHT",
    "PHASE3_WRITEBACK_BUNDLE",
    "PHASE3_CREATE_PR",
  }
  # map next_action -> runner command
  cmd = None
  if next_action in loop_actions:
    if not run_id:
      return stop_wait("RUN_ID_MISSING", f"next_action={next_action} requires run_id")
    cmd = ["python", str(RUNNER), "loop-resume", "--run-id", run_id]
  elif next_action in {"WAIT_PR_CHECKS", "WAIT_FOR_CHECKS", "WAIT_FOR_MERGE", "WAIT_PR_MERGE"}:
    if not run_id:
      return stop_wait("RUN_ID_MISSING", f"next_action={next_action} requires run_id")
    cmd = ["python", str(RUNNER), "merge-finish", "--run-id", run_id]
  elif next_action in {"WAIT_LOOP_ENGINE"}:
    if not run_id:
      return stop_wait("RUN_ID_MISSING", f"next_action={next_action} requires run_id")
    cmd = ["python", str(RUNNER), "loop-wait-refresh", "--run-id", run_id]
  elif next_action in {"CREATE_PR_FOR_RUN", "OPEN_NEW_PR_FOR_RUN"}:
    if not run_id:
      return stop_wait("RUN_ID_MISSING", f"next_action={next_action} requires run_id")
    cmd = ["python", str(RUNNER), "pr-create", "--run-id", run_id]
  elif next_action in {"READY_TO_APPLY_SAFE_PATH"}:
    if not run_id:
      return stop_wait("RUN_ID_MISSING", f"next_action={next_action} requires run_id")
    cmd = ["python", str(RUNNER), "apply-safe", "--run-id", run_id]
  elif next_action in {"STATUS", "BOOT"}:
    cmd = ["python", str(RUNNER), "status"]
  elif next_action in {"ALL_DONE"}:
    cmd = ["python", str(RUNNER), "compact"]
  elif next_action in {"MANUAL_RESOLUTION_REQUIRED", "PROVIDE_EVIDENCE_OR_ABORT"}:
    stop_result = _stop_from_reason_code(reason_code, stop_class)
    if stop_result is not None:
      return stop_result
    try:
      cmd = _runner_cmd_from_reason_code(reason_code, run_id)
    except RuntimeError as e:
      return stop_wait("RUN_ID_MISSING", str(e))
    if not cmd:
      return stop_wait(next_action, f"next_action={next_action} stop_class={stop_class} reason_code={reason_code}")
  else:
    return stop_wait("UNKNOWN_NEXT_ACTION", f"next_action={next_action} stop_class={stop_class} reason_code={reason_code}")
  # pass GH_REPO if present in run_state
  gh_repo = (rs.get("gh_repo") or rs.get("repo") or os.environ.get("GH_REPO") or "").strip()
  env = dict(os.environ)
  if gh_repo:
    env["GH_REPO"] = gh_repo
  rule = REASON_CODE_RULES.get(reason_code)
  if rule and next_action in {"MANUAL_RESOLUTION_REQUIRED", "PROVIDE_EVIDENCE_OR_ABORT"}:
    print(f"REASON_CODE_RULE={reason_code} category={rule.get('category','')}")
  print("AUTO_RESUME:", " ".join(cmd))
  p = subprocess.run(cmd, env=env, text=True, encoding="utf-8", errors="replace")
  try:
    rs_after = json.loads(RUN_STATE.read_text(encoding="utf-8")) if RUN_STATE.exists() else {}
    print(
      "SSOT_ADVANCED"
      f" next_action={rs_after.get('next_action','')}"
      f" run_status={rs_after.get('run_status','')}"
      f" updated_at={rs_after.get('updated_at','')}"
    )
  except Exception:
    pass
  if p.returncode == 0:
    try:
      _ensure_ssot_writeback_pr(run_id)
    except Exception as e:
      print(f"STOP_HARD: SSOT_WRITEBACK_FAILED\n{e}", file=sys.stderr)
      return 1
  else:
    print("SSOT_DIRTY=false")
  return p.returncode
if __name__ == "__main__":
  raise SystemExit(main())
