param()

$ErrorActionPreference = "Stop"

# ===== CHAT_PACKET_MIN generator (stable) =====
# - No accidental printing of "-replace" fragments
# - Uses UTF-8 (no BOM) output
# - Includes IDEA_INDEX if it exists (ideas become visible in the packet copy-paste)

$ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$head = (& git rev-parse HEAD).Trim()

# repo url (best-effort)
$repoUrl = ""
try {
  $repoUrl = (& git remote get-url origin).Trim()
} catch {
  $repoUrl = ""
}

# Files to embed (fixed read order + idea index if present)
$files = New-Object System.Collections.Generic.List[string]
$files.Add("docs/MEP/START_HERE.md")
$files.Add("docs/MEP/CHAT_STYLE_CONTRACT.md")
$files.Add("docs/MEP/STATE_CURRENT.md")
$files.Add("platform/MEP/90_CHANGES/CURRENT_SCOPE.md")
$files.Add("platform/MEP/03_BUSINESS/よりそい堂/master_spec")
$files.Add("platform/MEP/03_BUSINESS/よりそい堂/ui_spec.md")
$files.Add("docs/MEP/RUNBOOK.md")

# IDEA_INDEX (generated by mep_idea_capture) - include if present
if (Test-Path "docs/MEP/IDEA_INDEX.md") {
  $files.Add("docs/MEP/IDEA_INDEX.md")
}

# Header
Write-Output ("# CHAT_PACKET_MIN (MEP)  {0}" -f $ts)
Write-Output ""
Write-Output "## META"
if ($repoUrl) { Write-Output ("- repo: {0}" -f $repoUrl) } else { Write-Output "- repo: (unknown)" }
Write-Output ("- head: {0}" -f $head)
Write-Output ""
Write-Output "## BOOT RULE"
Write-Output "- New chat (memory=0): do NOT request 10+ files. Ask to paste this packet again if needed."
Write-Output "- Provide one-paste PowerShell blocks."
Write-Output ""
Write-Output "## NOTES"
Write-Output "- If IDEA_INDEX is present, ideas captured in this repo will be visible in this packet."
Write-Output ""

# Body: embed files verbatim (UTF-8 read), normalize to LF in output
foreach ($f in $files) {
  Write-Output ("--- BEGIN FILE: {0} ---" -f $f)
  if (Test-Path $f) {
    $raw = Get-Content -LiteralPath $f -Raw -Encoding UTF8
    if ($null -eq $raw) { $raw = "" }
    $raw = $raw -replace "`r`n", "`n"
    $raw = $raw -replace "`r", "`n"
    Write-Output $raw
  } else {
    Write-Output ("(MISSING) {0}" -f $f)
  }
  Write-Output ("--- END FILE: {0} ---" -f $f)
  Write-Output ""
}

Write-Output "## END"